version: '3'
services:
  core:
    image: "amcgee/dhis2-core:dev"
    restart: always
    volumes:
      - ./config/DHIS2_home:/DHIS2_home
    depends_on:
      - "db"
  db:
    image: "mdillon/postgis:10-alpine"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - datadb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dhis2
      POSTGRES_USER: dhis
      POSTGRES_PASSWORD: dhis
  gateway:
    image: "nginx:alpine"
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.apps:/data/apps:ro
volumes:
  datadb: