version: '3'
services:
  core:
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    volumes:
      - ./config/DHIS2_home:/DHIS2_home
  db:
    build: ./containers/db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - datadb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dhis2
      POSTGRES_USER: dhis
      POSTGRES_PASSWORD: dhis
volumes:
  datadb: